const wordList = {
    easy: [
        { word: "book", hint: "A set of written, printed, or blank pages." },
        { word: "sun", hint: "The star at the center of our solar system." },
        { word: "pizza", hint: "A popular round dish with toppings." },
        { word: "rain", hint: "Water droplets falling from clouds." },
        { word: "friend", hint: "Someone you like and trust." },
        { word: "moon", hint: "Earth’s natural satellite." },
        { word: "phone", hint: "A device used for communication." },
        { word: "school", hint: "A place where children learn." },
        { word: "music", hint: "A form of sound that is pleasing to hear." },
        { word: "tea", hint: "A popular hot beverage made from leaves." },
        { word: "juice", hint: "A drink made from fruit." },
        { word: "honey", hint: "A sweet substance made by bees." },
        { word: "cake", hint: "A dessert made from flour, sugar, and eggs." },
        { word: "egg", hint: "A food that comes from chickens." },
        { word: "burger", hint: "A popular sandwich with a meat patty." }
    ],
    
    medium: [
        { word: "bicycle", hint: "A human-powered vehicle with two wheels." },
        { word: "stadium", hint: "A place where sports matches are played." },
        { word: "hashtag", hint: "A symbol used to categorize posts on social media." },
        { word: "guitar", hint: "A musical instrument with strings." },
        { word: "camera", hint: "A device used to capture and record images or videos." },
        { word: "trophy", hint: "A cup-shaped award for winners." },
        { word: "cartoon", hint: "Animated characters shown on TV." },
        { word: "superhero", hint: "A fictional character with extraordinary powers." },
        { word: "history", hint: "The study of past events and human civilization." },
        { word: "diamond", hint: "A precious gemstone known for its brilliance and hardness." },
        { word: "coffee", hint: "A popular caffeinated beverage made from roasted coffee beans." },
        { word: "football", hint: "A popular sport played with a spherical ball." },
        { word: "fitness", hint: "The state of being physically healthy." },
        { word: "rainforest", hint: "A dense forest characterized by high rainfall and biodiversity." },
        { word: "butterfly", hint: "An insect with colorful wings and a slender body." },
        { word: "oasis", hint: "A fertile spot in a desert where water is found." },
        { word: "novel", hint: "A long work of fiction, typically with a complex plot and characters." },
        { word: "dance", hint: "A rhythmic movement of the body often performed to music." }
    ],
    
    hard: [
        { word: "paradox", hint: "A statement that contradicts itself." },
        { word: "architecture", hint: "The art of designing buildings." },
        { word: "astronomy", hint: "The study of celestial objects." },
        { word: "unpredictable", hint: "Something that cannot be foreseen." },
        { word: "illusion", hint: "A deceptive appearance or perception." },
        { word: "sculpture", hint: "A three-dimensional art form created by shaping materials." },
        { word: "symphony", hint: "A long musical composition for an orchestra." },
        { word: "language", hint: "A system of communication using words, gestures, and syntax." },
        { word: "theater", hint: "A building or outdoor area for performances." },
        { word: "orchestra", hint: "A large group of musicians playing various instruments." },
        { word: "technology", hint: "The application of scientific knowledge for practical purposes." },
        { word: "adventure", hint: "An exciting or daring experience." },
        { word: "astronaut", hint: "A person trained to travel and work in space." },
        { word: "waterfall", hint: "A cascade of water falling from a height." },
        { word: "shadow", hint: "A dark area produced by an object blocking light." },
        { word: "nostalgia", hint: "A sentimental longing for the past." },
        { word: "brilliant", hint: "Exceptionally clever, talented, or impressive." },
        { word: "mysterious", hint: "Difficult or impossible to understand, explain, or identify." }
    ]
};
